### PR TITLE
Feature/code move

### PR DESCRIPTION
**Pull request by alexflav23**
- Moving over all the code from the ONS Api repo for ingestion.

### CODE REVIEW

**Review by onscmhw — CHANGES_REQUESTED** [review]
Need a sample config file for relevant params, as the main application is reading from config.  Sample config file should use environment variables, not hard-coded URLs etc.

Also, Travis build is failing - do we need a travis.yaml file or something?

**Comment by alexflav23** [comment]
Hi @onscmhw,

I'll add the Travis conf straight up, and good call on the sample, I forgot, focusing on the mapping stuff, almost done.

**Review by onscmhw — CHANGES_REQUESTED** [review]
Where is the Spark "doStuff" code in the "data" project?  I'm seeing code to parse records and write records to ES, but nothing to load files or do stuff in between reading & writing the data.  Am I missing something, or is it just not committed yet?

**Review by onscmhw — CHANGES_REQUESTED** [review]
Compilation error in SBT with CompaniesHouseRecord case class breaking Scala 22-field limit.

**Pull request merged**
